### ISSUE TITLE
v3 schema-revision: contentType.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#101]
The `mediaType.schema.json` will be used to define the file format in accordance with media-types.

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/mediaType"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **name** [expects: free text, count: 1]
- **associatedFileExtensions** [expects: free text, count: 1 - N]
- **fullName** [expects: free text, count: 1]
- **synonyms** [expects: free text, count: 0 - N]
- **ianaRef** [expects: uri, count: 0 - 1]

**Comment by lzehl** [comment]
@apdavison could you have a look at the schema docu above and provide me with feedback?  
[I just created it based on my notes on the topic]

**Comment by apdavison** [comment]
I'm not sure how type, subtype and associatedFormat would be used. Can you give me an example, e.g. for application/pdf ?

**Comment by lzehl** [comment]
`associatedFormat` would be the full name of the file format, because that is not always identifiable from the media type name (which is a bit cryptic for most people). People would need to look it up externally if they don't get it in the information.    

`type` (e.g., `"application"`) and `subtype` (`"pdf"`are building the `name` (e.g., "application/pdf"), we could therefore also leave them out or ask for them explicitly and leave the `name` out. (`associatedFormat` would be then I guess "Adobe Portable Document Format")

@apdavison Did you already decided on the fields you wanted to capture for the media types?  
and what/how we need to define specifications of the media type to identify generic output formats of specific structure from a specific application? (e.g. json metadata file of QuickNII)

**Comment by apdavison** [comment]
thanks for the clarification. I suggest leaving out `type` and `subtype`, since they are easily retrievable from the name and are not very useful on their own. I suggest renaming `associatedFormat` to `fullName`or `description`, making it "count: 1", and then perhaps adding a `synonyms` field. Adding a `category` field might also be useful.

For minting our own, unofficial media types, I suggest something like the following, which I think is compatible with the various RFCs governing media types (https://tools.ietf.org/html/rfc6838, etc....):

  "application/vnd.{application}.{file-type}+{carrier-format}"

e.g. 

  "application/vnd.quicknii.metadata+json"

or possibly

  "application/vnd.{organisation}.{application}.{file-type}+{carrier-format}"

e.g. 

  "application/vnd.nest-initiative.nest.script+python"

**Comment by lzehl** [comment]
Sounds good! I'll adapt the documentation above. Any other fields missing you would like to have?

**Comment by lzehl** [comment]
TODO: rename to contentType.schema.json
