### ISSUE TITLE
file bundles?

### ISSUE THREAD

**Issue by tgbugs** [openMetadataInitiative/openMINDS_core#11]
Is the concept of a file bundle still present? I couldn't spot it in any of the schemas.

**Comment by lzehl** [comment]
Hi, yes, the concept of file bundles is still present. We played with the thought to only define one schema for a single file instance and a file bundle, because we basically asked the same thing for both, but came to the conclusion that we will handle them most likely separately in openMINDS v3.

Let's keep in touch about this. Best, Lyuba

**Comment by lzehl** [comment]
@tgbugs I'm closing this issue now. We can come back to it on the corresponding issue for the schema (coming soon).
