### ISSUE TITLE
feedback for modelVersion.schema.tpl.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#143]
@apdavison please have a look at the [modelVersion.schema.tpl.json](https://raw.githubusercontent.com/HumanBrainProject/openMINDS_core/v3/schemas/products/modelVersion.schema.tpl.json)

My question:
1) Is it correct that we agreed to link to a ContentType for the model format?

**Comment by apdavison** [comment]
yes, I think that makes the most sense

**Comment by lzehl** [comment]
@apdavison Perfect! Thank you for confirming again. The rest looks okay or do you miss something?

**Comment by apdavison** [comment]
@lzehl I've now started planning in detail the migration of model/model version metadata to openMINDS. I think the following changes are needed:

- move `studyTarget`, `scope`, and `abstractionLevel` from `ModelVersion` to `Model`. The reason is that if you change any of these things you have a new model, not just a new version
- for `inputData` and `outputData`, we need to allow links to `FileRepository`, `FileBundle` and `FileInstance`, in addition to `DigitalIdentifier`.

There is also the question of more fine-grained accessibility control, but I'll discuss that with you and Oli separately.

**Comment by lzehl** [comment]
@apdavison thanks for providing feedback on the model schemas.

To your first point: good to know, I'll change this asap.

The second point I would like to discuss. In principle the idea was the Digital Identifier can be also used to link to a FileRepository, FileBundle, and FileInstance (e.g. via the KG identifier for internally stored data or URI for externally stored data), but I can see that this might be cumbersome. Could you describe a short use case for me why the direct linkage would be better?

For the fine-grained accessibility control: please get in touch for setting up a discussion with me and Oli. I'm not sure what you mean here, but the controlled terms for the accessibility of a research product can be of course extended (it currently only covers the ones we decided for the dataset cases). If this is what you mean, please feel free to make suggestions for extending the controlled term list.

**Comment by apdavison** [comment]
Hi @Lyuba, sorry it's taken me so long to reply. For the links via DigitalIdentifier, my thinking is that for internal objects we should use the specific types, and keep DigitalIdentifier for links to external resources. Otherwise everything could just link via DigitalIdentifiers. For `inputData`, for example, not all objects with a DigitalIdentifier would be valid, only things that represent actual data files.

**Comment by lzehl** [comment]
@apdavison no worries. I know you are busy ;) I'm okay with adding the direct linkage possibility to the file schemas if this is too cumbersome otherwise.

The reason why we first decided for only going over the DigitalIdentifier instead was that this would push users to go with the official, citable DigitalIdentifier or at least provide a "howToCite" possibility. We also thought that would make it easier within the KG to identify which file (repository, bundle, instance) entries belong to which ResearchProductVersion: if the resource belongs to your research product you reference the file (repository, bundle, instance) entry, if the resource belongs to another product use the digital identifier.

What do you think? Does this initial thought makes sense or is it unnecessary?
@apdavison & @olinux it would be good to hear both of your opinions again on this before we decide which way to follow. I'm open for both approaches.

**Comment by lzehl** [comment]
@apdavison & @olinux if you agree, I would like to push this issue to the next revision for openMINDS. I think it's worth discussing a bit more before we come to a decision. For now I leave inputData and outputData as they are (linking to a digital identifier), but I completely agree that we may have to revise this decision

**Comment by apdavison** [comment]
@lzehl sure

**Comment by lzehl** [comment]
@apdavison the "inputData" can reference now to         
        "https://openminds.ebrains.eu/core/DOI",
        "https://openminds.ebrains.eu/core/File",
        "https://openminds.ebrains.eu/core/FileBundle",
        "https://openminds.ebrains.eu/core/URL"

I think this resolves the open points of this issue, correct? please let me know if we should add FileRepository to the list as well. Note that this requires strict curation rules: only point to FileRepo if input repository does not have a DOI.

**Comment by apdavison** [comment]
it's probably ok without FileRepository, so all is good.

**Comment by lzehl** [comment]
perfect. I'm closing the issue then and we can revise adding the FileRepo when we encounter a use case where this would be absolutely required.
