### ISSUE TITLE
Do not require contact information in schemas/actors/person.schema.tpl.json

### ISSUE THREAD

**Issue by apdavison** [openMetadataInitiative/openMINDS_core#148]
Research products may have contributors who do not have contact information (retired, left academia, deceased...)

**Comment by lzehl** [comment]
@apdavison this is a good point. We should make it not required. I'll take care of it asap.

Note: This change requires that we need to make clear to the EBRAINS curation team that even if not required all authors need to have contact information (email) if available, because of the new notification policy in the publication process the research product.

**Comment by lzehl** [comment]
This issue was solved :)
