### ISSUE TITLE
change name for next version ?

### ISSUE THREAD

**Issue by jcolomb** [openMetadataInitiative/openMINDS_core#15]
"openminds" gives too much hits on google and make the project difficult to find when one only has its name. (each time I want to come here, it takes me minutes...)

**Comment by lzehl** [comment]
Use hbp openminds :) that should lead you always to this project. We are historically bound to use MINDS, but needed a new name because MINDS is used in a similar context by another project. I'll keep it in mind though ( ^^ ). After a long discussion we agreed to openMINDS. Maybe we can add HBP or EBRAINS to the name. This is not my decision though, I need to discuss this in the curation team.
