### ISSUE TITLE
Simplification & ensurance of consistency in quantitative value range

### ISSUE THREAD

**Issue by olinux** [openMetadataInitiative/openMINDS_core#150]
Although it is comprehensible that a quantitative value range could potentially contain a max and a min value both with different units and uncertainty, I wonder if this actually makes sense since the interpretation of such a combination of different units is quite cumbersome. Additionally, this multi-level nesting can introduce additional complexity. I'm wondering if it would be ok to have a "minValue" (number), "maxValue" (number), "uncertainty" (for both) and "unit" (for both)!?

https://github.com/HumanBrainProject/openMINDS_core/blob/c2d69bd3b14a1bcbb3c8b5fedf937e8d391d72d8/schemas/miscellaneous/quantitativeValueRange.schema.tpl.json#L2

**Comment by lzehl** [comment]
@olinux thanks for bringing this up. Ulrike and I discussed it during the implementation of this schema and decided for the most consistent way.

Nonetheless I would like to leave this for discussion.
@UlrikeS91 , @skoehnen & @apdavison what do you think?

**Comment by UlrikeS91** [comment]
As @lzehl said, we discussed this when we decided for the additional schema. We also noticed that especially the unit is problematic, but possible to solve by curation. 
The reason we decided for each value to have its own uncertainty and unit, was mostly based on the uncertainty. I absolutely agree that both values should have the same unit, but there is absolutely no reason for the uncertainties to be the same. 
So, we wanted to keep it simple and not create an additional schema with the same properties as for the `quantitativeValue` schema just repeated twice (except for the unit). 
However, if @olinux  thinks that this would be more consistent and less error prone, I wouldn’t oppose to changing the schema. 
Then the schema would have the following properties: 
- maxValue (number)
- minValue (number)
- uncertaintyMax (array of 2 numbers)
- uncertainityMin (array of 2 numbers)
- unit (linking to unitOfMeasurement schema)

The instructions for the uncertainties would need to be crystal clear, though. Otherwise, people may mistake it for the min and max range of the uncertainty…

**Comment by lzehl** [comment]
@UlrikeS91 & @apdavison : I would be happy if we keep the structure as it is, but I could imagine the following alternative solution for **quantitativeValue** and **quantitativeValueRange**

**quantitativeValue** stays as it is (properties: _value_ [single number], _uncertainty_ [array of two numbers], _unit_ [valid for value and uncertainty]).

**quantitativeValueRange** could be further simplified from Ulrikes suggestion, because I think uncertainties for ranges are not typically used (@UlrikeS91 & @apdavison please provide counter examples if you disagree). For this reason the properties here could be reduced to maxValue [single number], minValue [single number], unit [valid for maxValue and minValue].

@UlrikeS91 & @apdavison & @skoehnen what do you think? keep the current setting or change it? if change it, would my suggestion fulfill our needs?

**Comment by UlrikeS91** [comment]
> **quantitativeValueRange** could be further simplified from Ulrikes suggestion, because I think uncertainties for ranges are not typically used (@UlrikeS91 & @apdavison please provide counter examples if you disagree). For this reason the properties here could be reduced to maxValue [single number], minValue [single number], unit [valid for maxValue and minValue].

There are probably several examples, but I think it would still be fine to simplify it anyway. You are right that ranges already reflect some uncertainty. It probably doesn't need to be any more specific than that. I can at least not see any example where this wouldn't be sufficient for our needs.

**Comment by lzehl** [comment]
@apdavison what do you think about this discussion? What would be your recommendation?

**Comment by apdavison** [comment]
I would support @lzehl's last suggestion, for the sake of simplicity. 

The `_instruction` string for QuantitativeValue needs more detail, by the way. Uncertainty can be expressed as +/- standard deviation, +/- standard error of the mean, 95% confidence intervals, etc.; the instruction needs to state which one is intended. Alternatively (and probably better due to the impossibility in general of converting between different measures of uncertainty) the type of uncertainty should probably be added as a property, with a set of controlled terms.

**Comment by lzehl** [comment]
@apdavison , @olinux , @UlrikeS91 , @jagru20 , @skoehnen 

I've made the following changes within the PR #168 :
1) simplification of **QuantitativeValueRange** to directly ask for properties `"maxValue" `(number; count:1), `"minValue"` (number; count:1), and `"unit"` (object; link to **controlledTerm/UnitOfMeasurement**; count:1)
2) modification of **QuantitativeValue** to also state property "typeOfUncertainty" (object; link to **controlledTerm/TypeOfUncertainty**; count:1)

For point 2 I already extended the controlledTerms to also hold a terminology for TypeOfUncertainty with two options at the moment (standardDeviation, standardError). The options for this controlledTerm need of course more details and the list needs to be extended.

**Comment by lzehl** [comment]
This issue was solved in PR #168. I close the issue now.
