### ISSUE TITLE
Laterality and "maxItem"

### ISSUE THREAD

**Issue by UlrikeS91** [openMetadataInitiative/openMINDS_core#153]
I've went through all schemas again and noticed that 5 schemas refer to `controlledTerms/laterality`:

**core:**
subjectGroupState --> handedness
subjectState --> handedness
tissueSampleCollection --> laterality
tissueSample --> laterality
**sands:**
annotation --> laterality

But `subjectGroupState` and `subjectState` don't use `"maxItem": 2`. Thinking about it, it may actually makes sense to remove it from the other ones, too. `controlledTerms/laterality` only has 2 options (left or right) and will never get more options (right? what would that be?). Therefore, with the restriction `"uniqueItems": true`, we can never select more than 2 items anyway. 

@lzehl, should we remove `"maxItems": 2` to simplify the other 3 schemas?

**Comment by lzehl** [comment]
@UlrikeS91 : yes. let's do the restriction via "uniqueItems".

Other question because you summarized it so nicely:
Should we rename the property "laterality" to "hemisphere" or "coveredHemisphere" or "hemibody" or "coveredHemibody" (to be more general).

@UlrikeS91 & @tgbugs what do you think?

**Comment by UlrikeS91** [comment]
I'm not sure if we should rename the property to any of your suggestions. They don't seem quite suitable. I think we ended up with "laterality" because this is used in anatomy quite frequently. My biggest issue is that it's usually used to describe dominance of one half over the other. But what we were aiming for is closer to the adjective “lateral” (= lying at or extending toward the right or left side: lying away from the median axis of the body). 
Hemisphere is too specific. Stupid anatomical example: Left and right foot. And I’m pretty sure several organs don’t have hemispheres in that sense… I’m not an expert, but a more neuro-related example is the spinal cord, right? I don’t think that one would refer to the two halves as hemispheres. 
I’m a bit unfamiliar with hemibody. Probably applies better, but it may still be too specific. 

Is there a(nother) word that sums up left/right in a broader sense?

**Comment by lzehl** [comment]
I agree that "hemisphere" is not really the correct term for all body parts.

I found "hemibody" used for medical descriptions to state the affected body half. 

I would be happy to find another term to "laterality". I personally associate this with the values "ipsilateral" and "bilateral" not with the actual side "left" / "right". 

Generally I would like to make more clear what is meant:
- From which side was the tissue sample / were the tissue samples extracted?
  -> could mean "extractionSide" for tissueSample and tissueSampleCollection
- In which side is the annotation defined?
  -> could mean "annotatedSide" 

But I do not like the word "Side" here because its ambiguous in its meaning. 
[e.g. "extractionSide" could be understood as the actual location, e.g. "left hippocampus" or "left big toe", not only "left" and "right"]

**Comment by lzehl** [comment]
@UlrikeS91 if we have handedness now separated; could we not add "bilateral" now to the laterality terms? 
Which would mean that we could set the expected value count to 1 for all of the remaining laterality linking schemas (solving also this issue)

core:
tissueSampleCollection --> laterality (count 1 because: left, right OR bilateral)
tissueSample --> laterality (count 1 because: left, right OR bilateral)
sands:
annotation --> laterality (count 1 because: left, right OR bilateral)

**Comment by UlrikeS91** [comment]
@lzehl, I don't think that "bilateral" would be quite suitable. It's more of a state rather than a description for “both halves of the bilateral organ have been used/delineated/etc.” Do you know what I mean?

I'm wondering if we may want to change this entirely: 
For both, `tissueSampleCollection` & `tissueSample`, you can specify the `laterality` of the samples. But in reality, this only makes sense if the `origin` is stated too. Additionally, even then `laterality` only makes sense if the `origin` is in fact something with a symmetry of sorts (e.g. bilateral organs like the brain or organ pairs like kidneys). Otherwise, stating “left” or “right” makes very little sense anyway. At the moment I could also state: 
`“laterality”: “controlledTerms/laterality/left”` + `”origin”: “controlledTerms/cellType/neuron”`.

This doesn’t actually make any sense without knowing what “left” relates, too. I can’t come up with a single example where `laterality` + `cellType` would work. Wouldn’t it make more sense to have `laterality` linked in the `organ` schema? 

For `annotation`, I’m not sure how this could be solved. Maybe it would be useful to include something similar to an `origin` (related or similar to the “inspiredBy” property) there as well? One could even argue that an `organ` should be an `anatomicalEntity`…

(Sorry if this makes it worse...)

**Comment by lzehl** [comment]
don't say sorry :wink: it's good when we discuss issues several times. Here my thoughts:

1) "bilateral": as far as I can see from my keyword search you can say "bilateral biopsy", "bilateral research design", "bilateral function", "bilateral leg pain", etc. vs. actually the word "unilateral". In that sense it does not completely fit with "left" and "right" body side, but on the other hand one is the specification of the other, e.g. (stupid example) "We did a unilateral surgery only considering the left side of the body" vs "We did a bilateral surgery". I agree that this of course only makes sense if we speak of a bilateral organ / anatomical structure, but this property is not required and can be left out if not applicable. 

2) "origin" was kicked out / replaced by "organ" (previously "organOfOrigin"). Adding laterality to the organ is unfortunately out of the question. On the one hand because the organ is a controlled term with a fixed set of properties, on the other hand the meaning would be ambiguous, because it could mean that this organ has a bilateral symmetry (e.g., kidney, brain, etc) / unilateral symmetry (e.g.,heart, liver, etc) OR was (e.g.) extracted or studied bilaterally / unilaterally (with spec. left / right). For annotations its more specific for the latter case (e.g., the delineation of that brain region was done bilaterally or unilaterally (with spec. left / right)). Nonetheless also here is a second case: also the delineation process was done bilaterally it could still be two annotations stored in two different files (one for each body side). 

3) maybe I just find your example confusing and misunderstood, but I don't know many use cases with natural tissue samples where the tissue sample is a neuron in the end (except for some insect /lower animal studies). Normally I would say you always end with a tissue sample in size of at least a biopsy piece which contains a neuron that might be targeted using a specific technique.

**Summarizing this I would like to discuss the following:**
In both cases (tissue sample and annotation) the question of laterality is tightly connected to the protocol execution producing the entity (e.g. did I do a bilateral or a unilateral biopsy/tissue extraction; did I do a bilateral or unilateral delineation) and has a second instance which provides you the detail on the product (e.g. unilateral tissue extraction to get the left brain hemisphere; unilateral delineation to define the left hippocampus)
  **a)** should the "lateralityOfProcedure" (terms: unilateral/bilateral) not be rather attached as optional field in the protocol/protocol execution?
  **b)** should in each affected entity (tissue sample , annotation) not be asked for the "includedBodySide" (left, right, both)?

Looking forward to your thoughts :wink:

**Comment by UlrikeS91** [comment]
> 1. "bilateral": as far as I can see from my keyword search you can say "bilateral biopsy", "bilateral research design", "bilateral function", "bilateral leg pain", etc. vs. actually the word "unilateral". In that sense it does not completely fit with "left" and "right" body side, but on the other hand one is the specification of the other, e.g. (stupid example) "We did a unilateral surgery only considering the left side of the body" vs "We did a bilateral surgery". I agree that this of course only makes sense if we speak of a bilateral organ / anatomical structure, but this property is not required and can be left out if not applicable.

Yes, uni- and bilateral can be used like this. It is for sure better than "left" and/or "right", but also a bit less specific since the unilateral side could be either.  


> 2. "origin" was kicked out / replaced by "organ" (previously "organOfOrigin"). Adding laterality to the organ is unfortunately out of the question. On the one hand because the organ is a controlled term with a fixed set of properties, on the other hand the meaning would be ambiguous, because it could mean that this organ has a bilateral symmetry (e.g., kidney, brain, etc) / unilateral symmetry (e.g.,heart, liver, etc) OR was (e.g.) extracted or studied bilaterally / unilaterally (with spec. left / right). For annotations its more specific for the latter case (e.g., the delineation of that brain region was done bilaterally or unilaterally (with spec. left / right)). Nonetheless also here is a second case: also the delineation process was done bilaterally it could still be two annotations stored in two different files (one for each body side).
> 3. maybe I just find your example confusing and misunderstood, but I don't know many use cases with natural tissue samples where the tissue sample is a neuron in the end (except for some insect /lower animal studies). Normally I would say you always end with a tissue sample in size of at least a biopsy piece which contains a neuron that might be targeted using a specific technique.

Hm... `origin` is the name of the property for `tissueSample` & `tissueSampleCollection` where you can choose from either `controlledTerms/organ` or `controlledTerms/cellType`. I think we decided to include `controlledTerms/cellType` specifically for artifical samples (produced in a dish). 
I understand the ambiguity you're describing in your second point, and agree that it's not optimal to add the (ex-)laterality to the organ-schema.  


> **Summarizing this I would like to discuss the following:**
> In both cases (tissue sample and annotation) the question of laterality is tightly connected to the protocol execution producing the entity (e.g. did I do a bilateral or a unilateral biopsy/tissue extraction; did I do a bilateral or unilateral delineation) and has a second instance which provides you the detail on the product (e.g. unilateral tissue extraction to get the left brain hemisphere; unilateral delineation to define the left hippocampus)
> **a)** should the "lateralityOfProcedure" (terms: unilateral/bilateral) not be rather attached as optional field in the protocol/protocol execution?
> **b)** should in each affected entity (tissue sample , annotation) not be asked for the "includedBodySide" (left, right, both)?


I generally like the idea to have the anatomical descriptions included at different levels. It would be fantastic if we were able to have increase the complexity a bit since there is so much more to it than bilateral systems. 
Generally speaking, there are several common symmetries in nature (e.g. https://en.wikipedia.org/wiki/Symmetry_in_biology). Reducing it to a single plan of symmetry (= bilateral) seems like a very strong oversimplification to me. 
Neuroscientifically speaking, bilaterality is still a simplification. For most cases, this would probably still suffice. But e.g. an octopus has several brains – one “main” one and several mini-brains (one per  arm I think). Pretty sure that uni- and bilateral will be difficult to use in such a case…  
I know this is probably a bit too much but I would already be happy if we could include something that describes "no laterality" (--> asymmetric/no plane of symmetry).

"includedBodySide" doesn't sound right to me somehow. It's probably correct, though.

**Comment by lzehl** [comment]
@UlrikeS91 we can close this now, correct? If so, please go ahead and close it :wink:

**Comment by lzehl** [comment]
This one was solved (I think) with #174

**Comment by UlrikeS91** [comment]
> @UlrikeS91 we can close this now, correct? If so, please go ahead and close it 😉

Oh! I missed this comment!

> This one was solved (I think) with #174

Yes, it is solved.
