### ISSUE TITLE
Reassessment of BehavioralTask

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#210]
Currently, the BehavioralTask are assumed to be ControlledTerms. Many of the behavioral tasks we are getting, are though not well defined and/or are not officially registered as a meaningful task. 

I would like to make this a bit more user-oriented and flexible by introducing a user-defined BehavioralTask schema with required properties "Full name", "Short name", "Description", + optional a selection of properties that link to controlled terms (with instances) for the used stimulus, task components, task structure, task rules, task cognitive system, motor readout, etc. (to be discussed).

If we reassess the registration of behavioral tasks this way, we can immediately take over most tasks of the old system as they were registered (and partially described) there and over time register the respective controlled terms (for at least some task aspects) to increase the knowledge integration between tasks.

Here some example instances for the possible controlled terms for a behavioral task (@tgbugs feel free to make more/better suggestions):

STIMULUS
- visual cue
  - natural image
  - static grid
  - moving grid 
  - ...
- auditory cue
  - cosine-squared tone
  - one syllable word
  - ...
- tactile cue
  - ...

TASK STRUCTURE
- go/no-go
- saccade/anti-saccade 
- instructed delayed motor response
- center out
- ...

TASK COGNITIVE SYSTEM
- attention
- working-memory
- ...

MOTOR READOUT
- tap left finger
- tap right finger
- squeeze left toes
- squeeze right toes
- reach and grasp

@olinux , @apdavison , @Peyman-N , @UlrikeS91 , @visakhmr , @MBAbrams please correct and comment.
What do you think? Please make suggestions also in respect to Tier-3 (so that we do not collide, but built on top of each other).

**Comment by jcolomb** [comment]
I hope this will not state the obvious. To my knowledge (which is restricted), attempts at ontologies for behavioural science failed. I was in a workshop in 2014 or 2015 (organised by Melissa Haendel ) and we realised that we could not agree on definitions, because much of it was dependent on the researcher's interpretation (that sometimes changes over time). 

In addition, description of behaviour seem to be very model system dependent, with human behaviour research being another world completely. For instance "motor readout" is very pregnant of an input-output view of behavior and behavior science, where others see and look for output-input problematics (actions). Also different motor outputs can get the same readout (different ways to press a lever for instance), the same assay could be used to test different things, etc

There is an issue between getting no information and getting a detailed information that the community would not agree on.


What people might better agree is on the behavioural setup used itself (more or less define the hardware and protocol used, not the behavior recorded):
- restrains (free moving, head-fixed, body-fixed, ...)
- reality setup (natural conditions, mechanical VR,  electronic VR in closed loop, electronic VR in open loop,...)
- setup readouts (lever press, licking behaviour, spacial position, movement speed (freezing-acceleration), poke, behaviour sequence, recorded noise, transcript of talking,...)

Maybe it would be worth contacting Melissa Haendel (melissa@tislab.org) to get her opinions and maybe an overview of existing taxonomies/ontologies ? 

Another strategy might be to look at what researchers would look for and see what metadata would be most useful ?

(PS: could not find what Tier-3 is.)

**Comment by lzehl** [comment]
@jcolomb first: sorry for the HBP / EBRAINS dialect... Here an explanation: Within HBP / EBRAINS we register metadata in 3 tiers. In **tier-1** "basic" metadata are registered (which is mainly covered via the schemas in openMINDS_core). They can go beyond pure bibliographic metadata, but can also stay rather superficial (user / use case dependent). In **tier-2** metadata that describe the anatomical location are covered as well as the identification of Brain Atlases according to the ontology model developed by Tom Gillespie and Heidi Kleven. This part is mainly covered via the schemas in openMINDS_SANDS. In **tier-3** in-depth metadata are registered that can cover the provenance of data. For this several openMINDS extensions are in development (e.g., openMINDS_computation). All tiers are interlinked and there is no clear border where one tier begins and one ends. The corresponding metadata models are of course interlinked as well.

**Comment by lzehl** [comment]
@jcolomb now for your actual comment: thanks a lot for these suggestions. We are well aware that ontologies for behavioral science is difficult. Therefore I want to first have a user defined instance in place that can be gradually complemented with controlled terminology to provide at least some data integration of the level of behavioral tasks. 

@tgbugs could you comment on @jcolomb suggestions and do you know Melissa Haendel? And could you maybe pin someone from BEADL? If we open that box we might as well do it completely :wink:

**Comment by tgbugs** [comment]
The objective here is precisely to avoid the issues of trying to ontologize behavior, thus the suggestion to describe the setup is exactly what we are going for (and we already have some of the "restraints" in the methods ontology).

In this approach the actual behavior of the organism (and the organism itself) is a black box. We want to capture the nomenclature used to describe everything around the behavior, but not the behavior itself. There is more agreement in the terminology used on the techniques/methods side of behavior which is why we are focusing on it.

**Comment by lzehl** [comment]
@jcolomb one additional remark on what @tgbugs responded: we also not necessarily immediately plan to create an ontology, but a set of controlled terminology for openMINDS (so we are less restrictive / do not need to be too precise). If these terms (cf. openMINDS_instances) later become / inspire an ontology development that would be great of course.

@olinux , @apdavison , @Peyman-N , @UlrikeS91 , @visakhmr , @MBAbrams , @tgbugs ,  (also @jcolomb) 

For now I will do the following:
I'll change the BehavioralTask from a controlledTerm to a core schema with the following properties:
+ Name (string; free text; required)
+ Description (string; free text; required)
+ Internal identifier (string; free text; optional) [e.g. the label or number used to identify which task was done in which recording]

Which additional (optional) properties should be attached to this schema which link then to controlled terms for aspect of the behavioral task we should further discuss and then add them over time. Please add your comments and remarks.

**Comment by jcolomb** [comment]
I like the plan :)

I would be nice to get a PID of some sort for this schema, or at least a reference link (doi to a paper explaining the task?). I am not sure how to implement it, though (protocols.io doi could do ?). 

I am not sure to understand what the internal identifier will be used for (id specific to each experimenter?)

**Comment by lzehl** [comment]
@jcolomb the "Internal identifier" should be maybe renamed... you are right that on this level the id specific to an experiment does not make much sense. Maybe we stick to "Full name" (instead of "name") and "Short name". 

An optional linkage to an external source / documentation (what would be a good property name?) might be useful. I would not like to link to papers that somewhere in the manuscript describe (typically very superficial) the used task , but maybe that's also better than nothing.

@tgbugs on the long run would it make sense to assign RRIDs to well documented behavioral tasks?

**Comment by Peyman-N** [comment]
Hello @lzehl 

I like the idea to have `BehavioralTask` as core schema. But in my opinion we need to have some additional properties as controlled term so we can group them. Otherwise they are going to be nodes with only one connection. But in reality they are interconnected and share some feature among themselves.  ( I was thinking maybe underlying mechanism can be a good option).

Concerning ontologies, the only online ontologie for behavioral task that I am aware of is [cognitive atlas](https://www.cognitiveatlas.org/tasks).

**Comment by lzehl** [comment]
@olinux , @apdavison , @Peyman-N , @UlrikeS91 , @visakhmr , @MBAbrams , @tgbugs 

I have another question: Would it make sense to treat the future Behavior(Protocol) schema same way as the Protocol schema? Meaning should the Protocol schema only be able to link to Techniques and the Protocol as well as the BehaviorProtocol schema should be linked to the ProtocolExecution schema via the property "protocol" (1-N) ?

**Comment by UlrikeS91** [comment]
@lzehl , given the latest updates to the `behavioralProtocol` schema (https://github.com/HumanBrainProject/openMINDS_core/pull/223), should this issue be close for now?

**Comment by lzehl** [comment]
@UlrikeS91 I would like to keep this open for further discussions and extensions of the behavior protocol

**Comment by lzehl** [comment]
I will close this issue and will open a new one that is targeting the assessment of the current BehavioralProtocol schema. This update will most likely be not part of the openMINDS release v3
