### ISSUE TITLE
Confusing "content" field in File

### ISSUE THREAD

**Issue by apdavison** [openMetadataInitiative/openMINDS_core#241]
For the File schema, the description of the “content” field is “Something that is contained” but the instruction is “Enter a short content description for this file instance”.

The field name and description imply that this field may contain the entire contents of the file (which you can imagine being useful for very small files that are accessed frequently, to save loading the file from the IRI).
The instruction says that this field should contain a description of the file contents.

To avoid this confusion (it confused me, at least), could we either (i) rename the field to “description” or (ii) change the description of the field?

**Comment by UlrikeS91** [comment]
@apdavison Do you think that description or content would semantically fit better as a property for the file? I think both would fit, but I'm not sure which one would be better. If I remember correctly, the idea for this field was to describe the content of the file so that a user would either have a first impression of the content before opening the file or doesn't need to open the file at all anymore (because the description gives them enough information).
  
If you think that "content" would be more suitable, the description for the field needs to change. I don't believe that @lzehl would insist on keeping "Something that is contained" as the description since it doesn't say much and probably was more like a placeholder (aka having something is better than nothing). 
If you think that "description" would be more suitable, would you say that its description ("Longer statement or account giving the characteristics of someone or something.") would suffices?

**Comment by xgui3783** [comment]
I had the exact experience with @apdavison , when generating a file object today. 

My interpretation is that `content` is intended to be `contentDescription`, per instruction on github pages.

**Comment by apdavison** [comment]
I presume this field is probably intended to contain a description of the file contents, as @xgui3783 says.

"description" or "contentDescription" would be better names.

**Comment by lzehl** [comment]
@apdavison and @UlrikeS91 the "description" of a property is a description of the term used as property. The "instruction" tell the user what that property means/what is expected as value. As for all property definitions we first went with the explanation most dictionary give for a term. The term "content" is defined in most dictionaries as "Something that is contained".  We went for the name "content" because that is what is used in the metadata of files typically for the content description (as far as we've checked I admid).

Nonetheless I like Andrews suggestion to rename it contentDescription. @apdavison do you make the PR or should I?
@olinux sorry that this requires another update in the KG...

**Comment by apdavison** [comment]
@lzehl I would prefer it if you make the PR (also, to be fair, "contentDescription" was Xiao's suggestion, not mine).

**Comment by lzehl** [comment]
Yes you are right @apdavison . Sorry @xgui3783 :sweat_smile: 
I'll make the PR then asap.
