### ISSUE TITLE
Question: Why is there no description for a schema?

### ISSUE THREAD

**Issue by ehennestad** [openMetadataInitiative/openMINDS_core#341]
Many properties have instructions and controlled terms have definitions and descriptions. Why is there no description for schemas?

**Comment by lzehl** [comment]
Dear @ehennestad schemas and properties also have descriptions but they are centrally defined and maintained on the openMINDS main Github (schemas are handled in types.json and properties are handled in properties.json).

We might lack behind some of the types and properties though because of the work load and many updates we had in the last year.
