### ISSUE TITLE
add content-type for voluba linear transformation json

### ISSUE THREAD

**Issue by xgui3783** [openMetadataInitiative/openMINDS_core#350]
We would like to propose the linear transformation json for voluba to be added to the content-type to openminds, and update voluba, so that the input and output is of this type. 

suggested mimetype:

`application/vnd.voluba.v1.linearTransform+json`

ping @fsdavid and perhaps @JThoennissen

We are happy to raise our own PR, if it suits everyone.

**Comment by xgui3783** [comment]
also maybe ping @skoehnen

**Comment by lzehl** [comment]
@xgui3783 that means that VoluBA currently only can do linear transformations? 

Can you quickly describe / correct the workflow for the input and output?
+ JSON as input: holds already the linear transformation needed to display input image in the BigBrain space (or a linear transformation in order to display input image in the BigBrain space, but that needs to be corrected)
+ JSON as output: contains the new linear transformation that was needed to place input image correctly in the BigBrain space

**Comment by lzehl** [comment]
If that fits feel free to make a PR

**Comment by xgui3783** [comment]
> that means that VoluBA currently only can do linear transformations?

This is accurate.

> JSON as input: holds already the linear transformation needed to display input image in the BigBrain space

This is correct

> JSON as output: contains the new linear transformation that was needed to place input image correctly in the BigBrain space

This is also correct.

**Comment by lzehl** [comment]
this issue was solved with #351
