### ISSUE TITLE
updating v3.0

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#67]
In the last weeks I had the chance to discuss a lot with Andrew, Benni and Oli about the latest version of v3.0 and started to develop a revised openMINDS model (documented elsewhere).

Although some details still need to be discussed the concept is now ready for pushing it on Github. 
This will include a complete change of the v3.0 Wiki and code and will take some time. 

We will do this update step-wise. Ulrike is going to support me in this updating process. 
This issue (and comments) will serve as progress table and discussion base. 

`@type` for the new schemas in v3.0 should follow (for now) this pattern:
`https://schema.ebrains/openminds/Capitalizedschemaname`

`@id` changes should still be discussed with Oli. 
For now we stick to the same principle as for the past schemas.

**Comment by lzehl** [comment]
@UlrikeS91 : I shared the external documents with you with the updated schemas. 
I will frequently update the following check list of schemas we need to edit:
- [x] `https://schema.ebrains/openminds/Project` (updated by Ulrike)
- [x] `https://schema.ebrains/openminds/Product` (updated by Ulrike)
- [ ] `https://schema.ebrains/openminds/Datasetversion` (updated by Ulrike)
- [ ] `https://schema.ebrains/openminds/Modelversion` (updated by Ulrike)
- [ ] `https://schema.ebrains/openminds/Softwareversion` (updated by Ulrike)

**Comment by UlrikeS91** [comment]
see #69

**Comment by UlrikeS91** [comment]
I've created product.schema.json and project.schema.json. 

Comments/Questions:

About project: "hasProduct" expects "productVersion" and/or "product" for now. The available documentation is inconsistent (one expects "product" while the other expects "productVersion"). Each version would make sense and I can see how both could be useful: We could have cases where only one version belongs to a certain project, but most cases will probably have the full product belonging to a project and then it would be more elegant if one could do that without adding each productVersion. 

I think that the solution could be to allow both options, which is why the project schema has both. 

About Product: "contributions" of course makes sense, but I'm wondering if this could be removed since it's implicit given that products cannot exist without productVersions (required field). The productVersion contributions may differ from version to version, but the overall product should then have all contributions from all productVersions, right?
If this continuous updating of the product contributions will cause issues with e.g. the globalID, it may even be smarter to remove the contributions all together? 

Additionally, I'm missing responsible person(s) in general (custodian(s), coordinator(s) or similar). Products could live without one if each productVersion would have one (which could in principle differ from version to version). If we don't want one for each version, then there should be a general responsible person for the product. Project could also use one, unless we say that all responsible persons for the attached products are also responsible for the project. 
Either way, I feel quite strongly about the fact that there is a need for a responsible person on some level.

**Comment by lzehl** [comment]
We will keep track of the v3 update differently (issue for each schema) to focus the discussions for each schema.
For this reason I'm closing this issue now.
